export const product = {
  cacheId: 'rustic-striped-vase',
  productName: 'Rustic Striped Vase',
  productId: '2000023',
  description: 'Beautiful rustic and striped vase for flowers.',
  titleTag: 'Rustic Striped Vase',
  metaTagDescription: 'Beautiful rustic and striped vase for flowers.',
  linkText: 'rustic-striped-vase',
  productReference: '999987',
  categoryId: '40',
  categories: ['/Home & Decor/'],
  brand: 'Kawasaki',
  brandId: 2000001,
  properties: [],
  specificationGroups: [
    {
      name: 'allSpecifications',
      specifications: [],
      __typename: 'SpecificationGroup',
    },
  ],
  items: [
    {
      itemId: '2000563',
      name: 'Rustic Striped Vase',
      nameComplete: 'Rustic Striped Vase',
      complementName: 'Handmade ceramic.',
      ean: '',
      referenceId: [
        {
          Key: 'RefId',
          Value: '999987',
          __typename: 'Reference',
        },
      ],
      measurementUnit: 'un',
      unitMultiplier: 1,
      images: [
        {
          imageId: '155517',
          imageLabel: 'rusticvase',
          imageTag:
            '<img src="~/arquivos/ids/155517-#width#-#height#/download--69-.png?v=636942440196570000" width="#width#" height="#height#" alt="rustic-vase" id="" />',
          imageUrl:
            'https://storecomponents.vteximg.com.br/arquivos/ids/155517/download--69-.png?v=636942440196570000',
          imageText: 'rustic-vase',
          __typename: 'Image',
        },
      ],
      videos: [],
      sellers: [
        {
          sellerId: '1',
          sellerName: 'VTEX',
          addToCartLink:
            'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=2000563&qty=1&seller=1&sc=1&price=0&cv=801c11e886cb596a5677ab2cfe4ca45a_&sc=1',
          sellerDefault: true,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 0,
            spotPrice: 0,
            ListPrice: 0,
            PriceWithoutDiscount: 0,
            RewardValue: 0,
            PriceValidUntil: null,
            AvailableQuantity: 0,
            Tax: 0,
            CacheVersionUsedToCallCheckout: '801c11e886cb596a5677ab2cfe4ca45a_',
            Installments: [],
            __typename: 'Offer',
          },
          __typename: 'Seller',
        },
      ],
      variations: [],
      kitItems: [],
      attachments: [],
      __typename: 'SKU',
    },
  ],
  itemMetadata: null,
  productClusters: [],
  clusterHighlights: [],
  __typename: 'Product',
}
